version: '3.8'

services:
  envioEmail-rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./configs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ms-user,ms-email
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      envioEmail-rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      SPRING_RABBITMQ_HOST: envioEmail-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-user
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BROKER_QUEUE_EMAIL_NAME: default.email
    networks:
      - app-network

  email-service:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: email-service
    depends_on:
      envioEmail-rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - 8082:8082
    environment:
      SPRING_RABBITMQ_HOST: envioEmail-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-email
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      BROKER_QUEUE_EMAIL_NAME: default.email
    networks:
      - app-network

volumes:
  rabbitmq-data:
  postgres-data:

networks:
  app-network:
    driver: bridge
